### ISSUE TITLE
generate-api   Please make sure that your schema is correct!

### ISSUE THREAD

**Issue by pfwd** [howToCodeWell/code-quiz#134]
When running `yarn run generate-api` The following error is reported
```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'Answer_jsonld_question_item__context_oneOf'.Please make sure that your schema is correct!
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:518)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:912)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:465)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class io.swagger.v3.oas.models.media.Schema (java.lang.Boolean is in module java.base of loader 'bootstrap'; io.swagger.v3.oas.models.media.Schema is in unnamed module of loader 'app')
        at org.openapitools.codegen.languages.TypeScriptClientCodegen.addAdditionPropertiesToCodeGenModel(TypeScriptClientCodegen.java:896)
        at org.openapitools.codegen.DefaultCodegen.updateModelForObject(DefaultCodegen.java:2726)
        at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:2951)
        at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1291)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:513)
        ... 4 more
error Command failed with exit code 1.
```

**Comment by pfwd** [comment]
Could be related to the following info message
```
[main] INFO  o.o.codegen.DefaultGenerator - Model Answer-question.item not generated since it's a free-form object
```

**Comment by pfwd** [comment]
Unsure if this is still an issue. I will need to check before closing
